// <auto-generated />
using System;
using HumanDesign.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanDesign.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501111235_InitialSqlServer")]
    partial class InitialSqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.Charts.CenterDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CenterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DesignId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DesignId", "CenterName")
                        .IsUnique();

                    b.ToTable("center_definition");
                });

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.Charts.DefinedChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("channel_id");

                    b.Property<Guid>("DesignId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("design_id");

                    b.Property<int>("GateA")
                        .HasColumnType("int")
                        .HasColumnName("gate_a");

                    b.Property<int>("GateB")
                        .HasColumnType("int")
                        .HasColumnName("gate_b");

                    b.HasKey("Id");

                    b.HasIndex("DesignId");

                    b.ToTable("defined_channels");
                });

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.Charts.Design", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("authority");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("definition");

                    b.Property<string>("IncarnationCross")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("incarnation_cross");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("profile");

                    b.Property<Guid>("ProspectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProspectId")
                        .IsUnique();

                    b.ToTable("design");
                });

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.Charts.PlanetaryActivation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Base")
                        .HasColumnType("int")
                        .HasColumnName("base");

                    b.Property<int>("Color")
                        .HasColumnType("int")
                        .HasColumnName("color");

                    b.Property<Guid>("DesignId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("design_id");

                    b.Property<string>("FixingState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fixation");

                    b.Property<int>("Gate")
                        .HasColumnType("int")
                        .HasColumnName("gate");

                    b.Property<int>("Line")
                        .HasColumnType("int")
                        .HasColumnName("line");

                    b.Property<string>("Planet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("planet");

                    b.Property<int>("Tone")
                        .HasColumnType("int")
                        .HasColumnName("tone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("DesignId");

                    b.ToTable("planetary_activations");
                });

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.Charts.VariableArrow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Base")
                        .HasColumnType("int")
                        .HasColumnName("base");

                    b.Property<int>("Color")
                        .HasColumnType("int")
                        .HasColumnName("color");

                    b.Property<bool>("IsLeft")
                        .HasColumnType("bit")
                        .HasColumnName("is_left");

                    b.Property<int>("Tone")
                        .HasColumnType("int")
                        .HasColumnName("tone");

                    b.HasKey("Id");

                    b.ToTable("variable_arrow");
                });

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.Charts.VariableSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AwarenessArrowId")
                        .HasColumnType("int");

                    b.Property<string>("Cognition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cognition");

                    b.Property<Guid>("DesignId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("design_id");

                    b.Property<string>("Digestion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("digestion");

                    b.Property<int>("DigestionArrowId")
                        .HasColumnType("int");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("environment");

                    b.Property<int>("EnvironmentArrowId")
                        .HasColumnType("int");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("motivation");

                    b.Property<string>("Perspective")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("perspective");

                    b.Property<int>("PerspectiveArrowId")
                        .HasColumnType("int");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reasoning");

                    b.HasKey("Id");

                    b.HasIndex("AwarenessArrowId");

                    b.HasIndex("DesignId")
                        .IsUnique();

                    b.HasIndex("DigestionArrowId");

                    b.HasIndex("EnvironmentArrowId");

                    b.HasIndex("PerspectiveArrowId");

                    b.ToTable("variables");
                });

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.FileEntity", b =>
                {
                    b.Property<int>("FileNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileNo"));

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("extension");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("path");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.HasKey("FileNo");

                    b.ToTable("file");
                });

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.Prospect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDateLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BirthDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("BirthLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("prospects");
                });

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.Reference.AttributeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detail");

                    b.Property<int?>("ImgNo")
                        .HasColumnType("int")
                        .HasColumnName("img-no");

                    b.Property<string>("Preview")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("preview");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("property");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("attributes");
                });

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.Reference.CenterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CenterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("definition");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detail");

                    b.Property<int?>("FileId")
                        .HasColumnType("int")
                        .HasColumnName("file_id");

                    b.Property<string>("Preview")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("preview");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.HasIndex("CenterName", "Definition")
                        .IsUnique();

                    b.ToTable("center");
                });

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.Reference.ChannelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detail");

                    b.Property<int?>("FileId")
                        .HasColumnType("int")
                        .HasColumnName("file_id");

                    b.Property<int>("GateA")
                        .HasColumnType("int")
                        .HasColumnName("gate_a");

                    b.Property<int>("GateB")
                        .HasColumnType("int")
                        .HasColumnName("gate_b");

                    b.Property<string>("Gift")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gift");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Preview")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("preview");

                    b.Property<string>("Shadow")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("shadow");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("summary");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("theme");

                    b.HasKey("Id");

                    b.ToTable("channel");
                });

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.Reference.CrossEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cross1")
                        .HasColumnType("int")
                        .HasColumnName("cross1");

                    b.Property<int?>("Cross2")
                        .HasColumnType("int")
                        .HasColumnName("cross2");

                    b.Property<int?>("Cross3")
                        .HasColumnType("int")
                        .HasColumnName("cross3");

                    b.Property<int?>("Cross4")
                        .HasColumnType("int")
                        .HasColumnName("cross4");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detail");

                    b.Property<int?>("FileId")
                        .HasColumnType("int")
                        .HasColumnName("file_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Preview")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("preview");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("summary");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("cross");
                });

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.Reference.GateEntity", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"));

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detail");

                    b.Property<int?>("FileId")
                        .HasColumnType("int")
                        .HasColumnName("file_id");

                    b.Property<string>("Preview")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("preview");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.HasKey("Number");

                    b.ToTable("gate");
                });

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.Reference.ProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code1")
                        .HasColumnType("int")
                        .HasColumnName("code1");

                    b.Property<int>("Code2")
                        .HasColumnType("int")
                        .HasColumnName("code2");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detail");

                    b.Property<int?>("FileId")
                        .HasColumnType("int")
                        .HasColumnName("file_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Preview")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("preview");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.ToTable("profile");
                });

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.Reference.TypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Characteristic")
                        .HasColumnType("int")
                        .HasColumnName("characteristic");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detail");

                    b.Property<int?>("FileId")
                        .HasColumnType("int")
                        .HasColumnName("file_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Preview")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("preview");

                    b.Property<int?>("Strategy")
                        .HasColumnType("int")
                        .HasColumnName("strategy");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("summary");

                    b.Property<int?>("Theme")
                        .HasColumnType("int")
                        .HasColumnName("theme");

                    b.HasKey("Id");

                    b.ToTable("type");
                });

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ReferralCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("referral_code");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("ParentId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.Charts.CenterDefinition", b =>
                {
                    b.HasOne("HumanDesign.Infrastructure.Entities.Charts.Design", null)
                        .WithMany("CenterDefinitions")
                        .HasForeignKey("DesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.Charts.DefinedChannel", b =>
                {
                    b.HasOne("HumanDesign.Infrastructure.Entities.Charts.Design", "Design")
                        .WithMany("Channels")
                        .HasForeignKey("DesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Design");
                });

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.Charts.Design", b =>
                {
                    b.HasOne("HumanDesign.Infrastructure.Entities.Prospect", "Prospect")
                        .WithOne("GeneratedDesign")
                        .HasForeignKey("HumanDesign.Infrastructure.Entities.Charts.Design", "ProspectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prospect");
                });

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.Charts.PlanetaryActivation", b =>
                {
                    b.HasOne("HumanDesign.Infrastructure.Entities.Charts.Design", "Design")
                        .WithMany("Activations")
                        .HasForeignKey("DesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Design");
                });

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.Charts.VariableSet", b =>
                {
                    b.HasOne("HumanDesign.Infrastructure.Entities.Charts.VariableArrow", "AwarenessArrow")
                        .WithMany()
                        .HasForeignKey("AwarenessArrowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanDesign.Infrastructure.Entities.Charts.Design", "Design")
                        .WithOne("Variables")
                        .HasForeignKey("HumanDesign.Infrastructure.Entities.Charts.VariableSet", "DesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanDesign.Infrastructure.Entities.Charts.VariableArrow", "DigestionArrow")
                        .WithMany()
                        .HasForeignKey("DigestionArrowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanDesign.Infrastructure.Entities.Charts.VariableArrow", "EnvironmentArrow")
                        .WithMany()
                        .HasForeignKey("EnvironmentArrowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanDesign.Infrastructure.Entities.Charts.VariableArrow", "PerspectiveArrow")
                        .WithMany()
                        .HasForeignKey("PerspectiveArrowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwarenessArrow");

                    b.Navigation("Design");

                    b.Navigation("DigestionArrow");

                    b.Navigation("EnvironmentArrow");

                    b.Navigation("PerspectiveArrow");
                });

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.Prospect", b =>
                {
                    b.HasOne("HumanDesign.Infrastructure.Entities.UserEntity", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.UserEntity", b =>
                {
                    b.HasOne("HumanDesign.Infrastructure.Entities.UserEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("HumanDesign.Infrastructure.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("HumanDesign.Infrastructure.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanDesign.Infrastructure.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("HumanDesign.Infrastructure.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.Charts.Design", b =>
                {
                    b.Navigation("Activations");

                    b.Navigation("CenterDefinitions");

                    b.Navigation("Channels");

                    b.Navigation("Variables")
                        .IsRequired();
                });

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.Prospect", b =>
                {
                    b.Navigation("GeneratedDesign");
                });

            modelBuilder.Entity("HumanDesign.Infrastructure.Entities.UserEntity", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
